version: "3"

services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
    ports:
      - 3000:3000

  backend:
    build:
      context: ./backend
    volumes:
      - ./data/images:/app/images
      - ./data/previews:/app/previews
      - ./backend/app:/app/app
    ports:
      - 8000:80
    env_file: .env.development
    command: ["--reload"]

  postgres:
    image: postgres:15.1-bullseye
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file: .env.development
